// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prhvwjzfpayezelqlmri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByaHZ3anpmcGF5ZXplbHFsbXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTI0MTEsImV4cCI6MjA2MDE4ODQxMX0.XpRRcUAqFrT2lEMc-4NgQFm79Eox0Wl4pOxjqdYSph8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);